spring:
    application:
      name: superman-user
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/account_center?useUnicode=true&characterEncoding=UTF8&autoReconnect=true
        username: root
        password: wduser
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # 配置初始化大小、最小、最大
        initial-size: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-open-prepared-statements: 20
    redis:
        host: 127.0.0.1
        port: 6379
        pool:
          max-active: 8
          max-idle: 8

mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.gome.superman.user.model,com.gome.superman.common.model


#Dubbo autoconfig

dubbo:
    name: superman-user-service
    registry: 127.0.0.1:2181
    port: -1
    timeout: 1000
    threads: 100
    heartBeats: 10000


# LOGGING
logging:
    config: classpath:logback-spring.xml
    #file: ${spring.application.name}.log
    path: /var/log/superman/${spring.application.name}
server:
  port: 8081
